# Generated by Django 5.2.3 on 2025-06-27 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leave',
            options={'ordering': ['-applied_at']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterField(
            model_name='leave',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Manager or supervisor who approved/rejected the leave', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Sick', 'Sick Leave'), ('Casual', 'Casual Leave'), ('Earned', 'Earned Leave')], help_text='Type of leave requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='leave',
            name='reason',
            field=models.TextField(help_text='Reason for the leave'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', help_text='Approval status of the leave', max_length=20),
        ),
        migrations.AlterField(
            model_name='leave',
            name='user',
            field=models.ForeignKey(help_text='Employee requesting the leave', on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='performance',
            name='feedback',
            field=models.TextField(help_text='Feedback comments by reviewer.'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='goal',
            field=models.TextField(blank=True, help_text='Optional goals set or evaluated.'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='reviewer',
            field=models.ForeignKey(blank=True, help_text='Employee who conducted the review.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='performance',
            name='score',
            field=models.IntegerField(help_text='Numeric score from 1–10.'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='user',
            field=models.ForeignKey(help_text='Employee who is being reviewed.', on_delete=django.db.models.deletion.CASCADE, related_name='performances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_by',
            field=models.ForeignKey(help_text='Manager or supervisor who assigned the task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(help_text='Employee who is assigned this task.', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', help_text='Current status of the task.', max_length=50),
        ),
    ]
